parameters:
  - name: RandomString1
    type: string
    default: ''
  - name: RandomString2
    type: string
    default: ''
  - name: RandomString3
    type: string
    default: ''
  - name: RandomString4
    type: string
    default: ''

jobs:
  - deployment: 'secondary_job'
    displayName: "${{ format ('Deploy {0} stage',  'Secondary') }}"
    pool:
      name: 'Default'
    environment: "Secondary"
    variables:
      - name: RandomString1
        value: ${{ parameters.RandomString1 }}
      - name: RandomString2
        value: ${{ parameters.RandomString2 }}
      - name: RandomString3
        value: ${{ parameters.RandomString3 }}
      - name: RandomString4
        value: ${{ parameters.RandomString4 }}  
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: PowerShell@2
              inputs:
                targetType: 'inline'
                script: 'Get-ChildItem Env: | Where-Object {$_.Name -like "RandomString*"} | Format-List'
                pwsh: true
              displayName: "Read Environment Variables"
              name: readEnvironmentVariables